"""Game development skill.

Scaffolds game projects, generates starter code, and prepares build/config files
for Godot, Unity, or Pygame. All actions are local file operations; no external
API keys required.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from jarvis_os.skills.base import Skill

logger = logging.getLogger(__name__)

# Default games directory inside the Jarvis OS project root.
DEFAULT_GAMES_DIR = Path(__file__).parent.parent.parent / "games"

# LLMs sometimes invent placeholder paths. Detect and ignore them.
_PLACEHOLDER_PATHS = ["/path/to", "/home/user", "/tmp", "/Users/user"]


def _resolve_project_dir(project_dir: str | None, default: Path) -> Path:
    """Use the provided directory unless it looks like an LLM placeholder."""
    if not project_dir:
        return default
    lowered = project_dir.lower().replace("\\", "/")
    for placeholder in _PLACEHOLDER_PATHS:
        if placeholder in lowered:
            return default
    return Path(project_dir).expanduser()


class GameDevSkill(Skill):
    """Create game project scaffolds and starter code."""

    name = "game_dev"
    description = (
        "Scaffold game projects: create Godot, Unity, or Pygame project files, "
        "generate starter scripts, and prepare build configurations."
    )
    schema = {
        "type": "object",
        "properties": {
            "action": {
                "type": "string",
                "enum": ["create_project", "generate_script", "list_engines"],
                "description": "Game dev action to perform.",
            },
            "engine": {
                "type": "string",
                "enum": ["godot", "unity", "pygame"],
                "description": "Game engine to use.",
            },
            "project_name": {
                "type": "string",
                "description": "Name of the game project.",
            },
            "project_dir": {
                "type": "string",
                "description": "Directory where the project should be created.",
            },
            "game_type": {
                "type": "string",
                "description": "Short description of the game, e.g. '2D platformer'.",
            },
            "script_name": {
                "type": "string",
                "description": "Name of the script to generate.",
            },
        },
        "required": ["action"],
    }
    permissions = ["file:write"]

    async def run(self, **kwargs: Any) -> dict[str, Any]:
        action = kwargs.get("action")
        if action == "create_project":
            return await self._create_project(kwargs)
        if action == "generate_script":
            return await self._generate_script(kwargs)
        if action == "list_engines":
            return {"engines": ["godot", "unity", "pygame"]}
        return {"error": f"Unknown action: {action}"}

    async def _create_project(self, kwargs: dict[str, Any]) -> dict[str, Any]:
        engine = kwargs.get("engine", "pygame")
        project_name = kwargs.get("project_name", "MyGame")
        project_dir = _resolve_project_dir(kwargs.get("project_dir"), DEFAULT_GAMES_DIR) / project_name
        game_type = kwargs.get("game_type", "arcade")

        if engine == "godot":
            return await self._create_godot_project(project_dir, project_name, game_type)
        if engine == "unity":
            return await self._create_unity_project(project_dir, project_name, game_type)
        if engine == "pygame":
            return await self._create_pygame_project(project_dir, project_name, game_type)
        return {"error": f"Unsupported engine: {engine}"}

    async def _create_godot_project(self, project_dir: Path, project_name: str, game_type: str) -> dict[str, Any]:
        project_dir.mkdir(parents=True, exist_ok=True)
        (project_dir / "project.godot").write_text(
            f"""; Engine Configuration File.
; Godot version: 4.x

[application]
config/name="{project_name}"
config/description="Autogenerated {game_type} game."
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.2", "Mobile")
config/icon="res://icon.svg"

[display]
window/size/viewport_width=1280
window/size/viewport_height=720

[autoload]
GameState="*res://scripts/game_state.gd"
""",
            encoding="utf-8",
        )

        scripts_dir = project_dir / "scripts"
        scripts_dir.mkdir(exist_ok=True)
        (scripts_dir / "game_state.gd").write_text(
            """extends Node

var score: int = 0
var health: int = 3

func add_points(points: int) -> void:
    score += points

func take_damage(amount: int) -> void:
    health -= amount
    if health <= 0:
        health = 0
""",
            encoding="utf-8",
        )

        (project_dir / "main.tscn").write_text(
            """[gd_scene load_steps=2 format=3 uid="uid://main"]

[ext_resource type="Script" path="res://scripts/main.gd" id="1_main"]

[node name="Main" type="Node2D"]
script = ExtResource("1_main")
""",
            encoding="utf-8",
        )

        (scripts_dir / "main.gd").write_text(
            f"""extends Node2D

func _ready() -> void:
    print("Welcome to {project_name} - a {game_type} game!")

func _process(delta: float) -> void:
    pass
""",
            encoding="utf-8",
        )

        return {
            "action": "create_project",
            "engine": "godot",
            "project_dir": str(project_dir),
            "files_created": ["project.godot", "main.tscn", "scripts/game_state.gd", "scripts/main.gd"],
            "next_step": "Open project.godot in Godot 4.x and run the main scene.",
        }

    async def _create_unity_project(self, project_dir: Path, project_name: str, game_type: str) -> dict[str, Any]:
        project_dir.mkdir(parents=True, exist_ok=True)
        assets_dir = project_dir / "Assets"
        assets_dir.mkdir(exist_ok=True)

        (project_dir / ".vsconfig").write_text(
            "{\n  \"version\": \"1.0\",\n  \"components\": []\n}\n",
            encoding="utf-8",
        )

        scripts_dir = assets_dir / "Scripts"
        scripts_dir.mkdir(exist_ok=True)
        (scripts_dir / "GameManager.cs").write_text(
            f"""using UnityEngine;

public class GameManager : MonoBehaviour
{{
    public int Score {{ get; private set; }}
    public int Health {{ get; private set; }} = 3;

    void Start()
    {{
        Debug.Log($"{{game_type}} game '{{project_name}}' started.");
    }}

    public void AddScore(int points)
    {{
        Score += points;
    }}

    public void TakeDamage(int damage)
    {{
        Health -= damage;
        if (Health <= 0)
        {{
            Debug.Log("Game Over");
        }}
    }}
}}
""",
            encoding="utf-8",
        )

        return {
            "action": "create_project",
            "engine": "unity",
            "project_dir": str(project_dir),
            "files_created": [".vsconfig", "Assets/Scripts/GameManager.cs"],
            "next_step": "Open the project folder in Unity Hub and add a scene with the GameManager script.",
        }

    async def _create_pygame_project(self, project_dir: Path, project_name: str, game_type: str) -> dict[str, Any]:
        project_dir.mkdir(parents=True, exist_ok=True)
        (project_dir / "main.py").write_text(
            f"""\"\"\"{project_name} - a {game_type} game built with Pygame.\"\"\"

import pygame
import sys

pygame.init()

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
pygame.display.set_caption("{project_name}")
clock = pygame.time.Clock()


def main() -> None:
    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        screen.fill((30, 30, 30))
        # TODO: draw game world here
        pygame.display.flip()
        clock.tick(FPS)

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()
""",
            encoding="utf-8",
        )

        (project_dir / "requirements.txt").write_text("pygame>=2.5.0\n", encoding="utf-8")

        (project_dir / "README.md").write_text(
            f"""# {project_name}

A {game_type} game built with Pygame.

## Run

```bash
pip install -r requirements.txt
python main.py
```
""",
            encoding="utf-8",
        )

        return {
            "action": "create_project",
            "engine": "pygame",
            "project_dir": str(project_dir),
            "files_created": ["main.py", "requirements.txt", "README.md"],
            "next_step": "Run 'pip install -r requirements.txt && python main.py' to test.",
        }

    async def _generate_script(self, kwargs: dict[str, Any]) -> dict[str, Any]:
        engine = kwargs.get("engine", "pygame")
        script_name = kwargs.get("script_name", "player")
        project_dir = _resolve_project_dir(kwargs.get("project_dir"), DEFAULT_GAMES_DIR / "MyGame")
        game_type = kwargs.get("game_type", "arcade")

        if engine == "godot":
            scripts_dir = project_dir / "scripts"
            scripts_dir.mkdir(parents=True, exist_ok=True)
            path = scripts_dir / f"{script_name}.gd"
            path.write_text(
                f"""extends CharacterBody2D

@export var speed: float = 300.0

func _physics_process(delta: float) -> void:
    var direction := Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
    velocity = direction * speed
    move_and_slide()
""",
                encoding="utf-8",
            )
        elif engine == "unity":
            scripts_dir = project_dir / "Assets" / "Scripts"
            scripts_dir.mkdir(parents=True, exist_ok=True)
            path = scripts_dir / f"{script_name}.cs"
            path.write_text(
                f"""using UnityEngine;

public class {script_name.capitalize()} : MonoBehaviour
{{
    public float speed = 5f;

    void Update()
    {{
        float h = Input.GetAxis("Horizontal");
        float v = Input.GetAxis("Vertical");
        Vector3 movement = new Vector3(h, 0, v) * speed * Time.deltaTime;
        transform.Translate(movement);
    }}
}}
""",
                encoding="utf-8",
            )
        elif engine == "pygame":
            scripts_dir = project_dir / "scripts"
            scripts_dir.mkdir(parents=True, exist_ok=True)
            path = scripts_dir / f"{script_name}.py"
            path.write_text(
                f"""import pygame

class {script_name.capitalize()}:
    def __init__(self, x: float, y: float) -> None:
        self.x = x
        self.y = y
        self.speed = 300
        self.color = (0, 200, 255)
        self.radius = 20

    def update(self, dt: float, keys) -> None:
        if keys[pygame.K_LEFT]:
            self.x -= self.speed * dt
        if keys[pygame.K_RIGHT]:
            self.x += self.speed * dt
        if keys[pygame.K_UP]:
            self.y -= self.speed * dt
        if keys[pygame.K_DOWN]:
            self.y += self.speed * dt

    def draw(self, surface: pygame.Surface) -> None:
        pygame.draw.circle(surface, self.color, (int(self.x), int(self.y)), self.radius)
""",
                encoding="utf-8",
            )
        else:
            return {"error": f"Unsupported engine: {engine}"}

        return {
            "action": "generate_script",
            "engine": engine,
            "script": str(path),
            "note": f"Add this {engine} script to your {game_type} scene.",
        }
